[config]
learning_rate = [0.025,0.02]
train_logger_display=2000 #number of batches after which the training performance is displayed
train_logger_flush=-1
verbose_train = 0
batchsize = 32
fixed_batchsize = true
shuffle_train=true


label_modifier = {name="ClassificationLabels", column="particle_type", classes={class1 = [12,-12,14,-14],class2 = [13, -13, 0]},model_output="bg_output" }
dataset_modifier = 'as_recarray'
sample_modifier = {name='GraphEdgeConv', knn=40}
