[model]
input_opts = {names = ["nodes", "is_valid", "coords"]}
type = "DisjointEdgeConvBlock"
next_neighbors = 40
shortcut = true

blocks = [
    {units=[64, 64, 64], to_disjoint=true, batchnorm_for_nodes=true},
    {units=[128, 128, 128]},
    {units=[256, 256, 256], pooling=true},
    {type='OutputRegNormal', output_name='dir',output_neurons=3}
]

[compile]
optimizer = "adam"

[compile.losses]
dir = {function='lkl_normal'}
