[config]
learning_rate = [0.005,0.01]
train_logger_display=1000 #number of batches after which the training performance is displayed
train_logger_flush=-1
verbose_train = 0
batchsize = 32
fixed_batchsize = true
shuffle_train=true

label_modifier = {name='RegressionLabels', columns=['visible_energy'], model_output='energy', stacks=2, log10=true} #create "visible_energy" in the extractor (orcasong)
dataset_modifier = 'as_recarray_dist'
sample_modifier = {name='GraphEdgeConv', knn=40}
