# Define the files for network training and validation in the toml format.
#
# For each set of files, give a name and an array of train files and validation files.
# Networks are directly fed from these files, if they have an input layer with the same name.
#
# Example format:
# -----------------------------
# [input_A]
# train_files = [
# "path/to/train_file_1_inputx.h5",
# "path/to/train_file_2_inputx.h5",
# ]
#
# validation_files = [
# "path/to/val_file_1_inputx.h5",
# ]
#
# [input_B]
# train_files = [
# "path/to/train_file_1_inputy.h5",
# "path/to/train_file_2_inputy.h5",
# ]
#
# validation_files = [
# "path/to/val_file_1_inputy.h5",
# ]
# -----------------------------

[xyz-t]
train_files = [
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_0_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_1_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_2_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_3_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_4_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_5_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_6_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_7_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_8_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_9_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_10_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_11_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_12_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_13_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_14_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_15_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_16_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_17_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_18_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_19_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_20_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_21_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_22_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_23_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_24_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_25_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_26_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_27_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_train_28_shuffled.h5",
]

validation_files = [
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_validate_0_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzt/data_split/xyzt_tight_0_100b_bg_classifier_dataset_validate_1_shuffled.h5",
]

[xyz-c]
train_files = [
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_0_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_1_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_2_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_3_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_4_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_5_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_6_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_7_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_8_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_9_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_10_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_11_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_12_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_13_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_14_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_15_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_16_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_17_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_18_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_19_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_20_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_21_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_22_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_23_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_24_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_25_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_26_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_27_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_train_28_shuffled.h5",
]

validation_files = [
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_validate_0_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_0_100b_t_bg_classifier/data_splits/xyzc/data_split/xyzc_tight_0_100b_bg_classifier_dataset_validate_1_shuffled.h5",
]




