# Info for building an OrcaNet model.

[body]
architecture = "single"

# default values for the trunk layers of the network:
type = "conv_block"
conv_dim = 3
kernel_size = 3
dropout = 0.0
activation = 'relu'
batchnorm=true


# config of every layer block, will overwrite the default values above
blocks = [
          {filters=64},
          {filters=64},
          {filters=64},
          {filters=64},
          {filters=64},
          {filters=64, pool_size=[2, 2, 2]},
          {filters=128},
          {filters=128},
          {filters=128},
          {filters=128, pool_size=[2, 2, 2]},
          ]

# ----------------------------------------------------------------------
[head]
architecture = "categorical"
architecture_args = {output_name='bg_output', categories=3}


# ----------------------------------------------------------------------
[compile]
optimizer = "adam"

[compile.losses]
bg_output = {function="categorical_crossentropy", metrics=['acc']}

# ----------------------------------------------------------------------
[orca_modifiers]
sample_modifier = 'xyz-t_and_xyz-c_single_input'
label_modifier = 'bg_classifier'
dataset_modifier = 'bg_classifier'
