# ParticleNet, using my custom DisjointEdgeConv block
# in the config, its mandatory to use the fixed_batchsize option
# use a sample_modifier to produce the 3 given inputs

[model]
# specify options for the input of the model
input_opts = {names = ["nodes", "is_valid", "coords"]}

type = "DisjointEdgeConvBlock"
next_neighbors = 16
shortcut = true

blocks = [
    {units=[64, 64, 64], to_disjoint=true, batchnorm_for_nodes=true},
    {units=[128, 128, 128]},
    {units=[256, 256, 256], pooling=true},
    {type="OutputCateg", transition=false, output_name="your_output_name_here", categories=3}
]

# ----------------------------------------------------------------------
[compile]
optimizer = "adam"

[compile.losses]
your_output_name_here = {function="categorical_crossentropy", metrics=['acc']}