#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This utility code contains functions that save the histograms (generated by hits_to_histograms) to .h5 files"""

import h5py
import numpy as np


def store_3d_histogram_as_hdf5(all_4d_to_3d_hists, tracks, filename_output):
    """
    Takes the 3D np histograms ('images') as well as the mc_info ('tracks') and saves them to a h5 file. 
    :param list all_4d_to_3d_hists: contains all 3D np histograms (ndarrays(ndim=2))
    :param ndarray(ndim=2) tracks: 2D array containing important MC information for each event_id. [event_id, particle_type, energy, isCC]
    :param filename_output: placeholder filename till production
    """

    hists_3d_xyz = np.array(all_4d_to_3d_hists)[:, 0]

    h5f = h5py.File('Results/4dTo3d/h5/' + filename_output + '_xyz.h5', 'w')
    dset_tracks = h5f.create_dataset('tracks', data=tracks)
    dset_xyz = h5f.create_dataset('xyz', data=hists_3d_xyz)

    h5f.close()