# Define the files for network training and validation in the toml format.
#
# For each set of files, give a name and an array of train files and validation files.
# Networks are directly fed from these files, if they have an input layer with the same name.
#
# Example format:
# -----------------------------
# [input_A]
# train_files = [
# "path/to/train_file_1_inputx.h5",
# "path/to/train_file_2_inputx.h5",
# ]
#
# validation_files = [
# "path/to/val_file_1_inputx.h5",
# ]
#
# [input_B]
# train_files = [
# "path/to/train_file_1_inputy.h5",
# "path/to/train_file_2_inputy.h5",
# ]
#
# validation_files = [
# "path/to/val_file_1_inputy.h5",
# ]
# -----------------------------

[xyz-t_0]
train_files = [
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_train_0_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_train_1_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_train_2_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_train_3_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_train_4_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_train_5_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_train_6_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_train_7_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_train_8_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_train_9_shuffled.h5",
]

validation_files = [
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier_no_cut/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_no_cut_validate_0.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier_no_cut/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_no_cut_validate_1.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier_no_cut/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_no_cut_validate_2.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier_no_cut/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_no_cut_validate_3.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier_no_cut/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_no_cut_validate_4.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier_no_cut/data_splits/xyzt/data_split/xyzt_tight_1_60b_ts_dataset_no_cut_rest_0.h5",
]

[xyz-c_0]
train_files = [
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_train_0_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_train_1_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_train_2_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_train_3_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_train_4_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_train_5_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_train_6_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_train_7_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_train_8_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_train_9_shuffled.h5",
]

validation_files = [
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier_no_cut/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_no_cut_validate_0.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier_no_cut/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_no_cut_validate_1.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier_no_cut/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_no_cut_validate_2.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier_no_cut/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_no_cut_validate_3.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier_no_cut/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_no_cut_validate_4.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_1_60b_ts_classifier_no_cut/data_splits/xyzc/data_split/xyzc_tight_1_60b_ts_dataset_no_cut_rest_0.h5",
]


[xyz-t_1]
train_files = [
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_train_0_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_train_1_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_train_2_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_train_3_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_train_4_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_train_5_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_train_6_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_train_7_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_train_8_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_train_9_shuffled.h5",
]

validation_files = [
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier_no_cut/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_no_cut_validate_0.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier_no_cut/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_no_cut_validate_1.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier_no_cut/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_no_cut_validate_2.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier_no_cut/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_no_cut_validate_3.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier_no_cut/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_no_cut_validate_4.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier_no_cut/data_splits/xyzt/data_split/xyzt_tight_2_60b_ts_dataset_no_cut_rest_0.h5",
]

[xyz-c_1]
train_files = [
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_train_0_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_train_1_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_train_2_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_train_3_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_train_4_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_train_5_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_train_6_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_train_7_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_train_8_shuffled.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_train_9_shuffled.h5",
]

validation_files = [
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier_no_cut/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_no_cut_validate_0.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier_no_cut/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_no_cut_validate_1.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier_no_cut/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_no_cut_validate_2.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier_no_cut/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_no_cut_validate_3.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier_no_cut/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_no_cut_validate_4.h5",
"/home/saturn/capn/mppi033h/Data/input_images/ORCA_2016_115l/tight_2_60b_ts_classifier_no_cut/data_splits/xyzc/data_split/xyzc_tight_2_60b_ts_dataset_no_cut_rest_0.h5",
]




