# These options define the various properties of a model.
#
# They overwrite the default values which are listed in the definition of the Configuration class.
#
[config]
zero_center_folder = "/home/woody/capn/mppi033h/orcanet_test/zero_center_folder/"
train_logger_display=250
train_logger_flush=-1
verbose_train = 1
#n_events = 32000