# Define the files for network training and validation in the toml format.
#
# Give an array of train files and validation files. Every dataset is started with the line [[input]].
# So if your network has multiple inputs, mark each seperate dataset with [[input]].
#
# Example format:
# -----------------------------
# [[input]]
# train_files = [
# "path/to/train_file_1_inputx.h5",
# "path/to/train_file_2_inputx.h5",
# ]
#
# validation_files = [
# "path/to/val_file_1_inputx.h5",
# ]
#
# [[input]]
# train_files = [
# "path/to/train_file_1_inputy.h5",
# "path/to/train_file_2_inputy.h5",
# ]
#
# validation_files = [
# "path/to/val_file_1_inputy.h5",
# ]
# -----------------------------

[[input]]
train_files = [
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/time_-250+500_w_gf_60b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzt_train_file_0_shuffled_0.h5",
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/time_-250+500_w_gf_60b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzt_train_file_1_shuffled_0.h5",
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/time_-250+500_w_gf_60b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzt_train_file_2_shuffled_0.h5",
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/time_-250+500_w_gf_60b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzt_train_file_3_shuffled_0.h5",
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/time_-250+500_w_gf_60b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzt_train_file_4_shuffled_0.h5",
]

validation_files = [
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/time_-250+500_w_gf_60b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzt_test_file_0_shuffled_0.h5",
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/time_-250+500_w_gf_60b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzt_test_file_1_shuffled_0.h5",
]


[[input]]
train_files = [
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_train_file_0_shuffled_0.h5",
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_train_file_1_shuffled_0.h5",
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_train_file_2_shuffled_0.h5",
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_train_file_3_shuffled_0.h5",
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_train_file_4_shuffled_0.h5",
]

validation_files = [
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_test_file_0_shuffled_0.h5",
"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_test_file_1_shuffled_0.h5",
]


